#!/bin/bash

# Quick script to complete modules 7-13 with proper math formatting

BASE="/home/samueldnvn4/.openclaw/workspace/hexapod-robot-engineering/lessons"

cat > "$BASE/07-kinematics.html" << 'EOF'
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Module 7</title><link rel="stylesheet" href="../css/styles.css"><script>MathJax = {tex: {inlineMath: [['\\(','\\)']], displayMath: [['$$','$$']]}}; </script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script><script src="../js/navigation.js"></script><script src="../js/problems.js"></script><script src="../js/quizzes.js"></script></head><body><header><div class="header-content"><h1>MODULE 7: KINEMATICS</h1><p class="subtitle">Forward/Inverse Kinematics, Jacobian</p></div></header><main class="container"><div class="progress-container"><div class="progress-bar"></div><div class="progress-text">0% Complete</div></div><section class="content-section"><h2>Module Overview</h2><p>Kinematics determines how joint angles map to end-effector positions (FK) and what joint angles achieve desired positions (IK). Essential for gait planning.</p><div class="important-box"><h3>Forward Kinematics</h3><p>Given \(\vec{\theta}\), compute \(\vec{x}: \vec{x} = f_{FK}(\vec{\theta}).\) Maps joint to task space.</p></div><div class="important-box"><h3>Inverse Kinematics</h3><p>Given \(\vec{x}_{desired},\), compute \(\vec{\theta}: \vec{\theta} = f_{IK}^{-1}(\vec{x}_{desired}).\) Mapping from task to joint space.</p></div><div class="important-box"><h3>Jacobian</h3><p>\(\dot{x} = J\dot{\theta}.\) Relates joint velocities to end-effector velocities. Singularity when \(\det(J) = 0.\)</p></div><section class="quiz-section"><h2>Module Quiz</h2><div id="quiz-container"></div><button class="submit" onclick="module7Quiz()">Submit Quiz</button><div id="quiz-results"></div></section><div class="nav-buttons"><button class="secondary" onclick="navigateTo('06-differential-equations.html')">Previous</button><button onclick="navigateTo('08-vibrations-waves.html')">Next</button></div></main><footer><p>Module 7</p></footer><script>function module7Quiz(){submitQuiz('07').percentage>=70&&markModuleComplete('07');}window.addEventListener("load",function(){updateProgressBar();});</script></body></html>
EOF

cat > "$BASE/08-vibrations-waves.html" << 'EOF'
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Module 8</title><link rel="stylesheet" href="../css/styles.css"><script>MathJax = {tex: {inlineMath: [['\\(','\\)']], displayMath: [['$$','$$']]}}; </script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script><script src="../js/navigation.js"></script><script src="../js/problems.js"></script><script src="../js/quizzes.js"></script></head><body><header><div class="header-content"><h1>MODULE 8: VIBRATIONS & WAVES</h1><p class="subtitle">Free/Forced Vibrations, Resonance</p></div></header><main class="container"><div class="progress-container"><div class="progress-bar"></div><div class="progress-text">0% Complete</div></div><section class="content-section"><h2>Module Overview</h2><p>Vibrations affect hexapod structural integrity. Understanding natural frequency and resonance ensures safe operation without destructive oscillations.</p><div class="important-box"><h3>Free Vibration</h3><p>Natural frequency: \(\omega_n = \sqrt{k/m}.\) Underdamped (\(\zeta < 1\)) oscillates: \(x(t) = e^{-\zeta\omega_nt}(C_1\cos\omega_dt + C_2\sin\omega_dt).\)</p></div><div class="important-box"><h3>Forced Vibration</h3><p>\(m\ddot{x} + c\dot{x} + kx = F_0\cos(\omega t).\) Resonance when \(\omega \approx \omega_n\) causes large amplitude.</p></div><section class="quiz-section"><h2>Module Quiz</h2><div id="quiz-container"></div><button class="submit" onclick="module8Quiz()">Submit Quiz</button><div id="quiz-results"></div></section><div class="nav-buttons"><button class="secondary" onclick="navigateTo('07-kinematics.html')">Previous</button><button onclick="navigateTo('09-control-theory.html')">Next</button></div></main><footer><p>Module 8</p></footer><script>function module8Quiz(){submitQuiz('08').percentage>=70&&markModuleComplete('08');}window.addEventListener("load",function(){updateProgressBar();});</script></body></html>
EOF

cat > "$BASE/09-control-theory.html" << 'EOF'
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Module 9</title><link rel="stylesheet" href="../css/styles.css"><script>MathJax = {tex: {inlineMath: [['\\(','\\)']], displayMath: [['$$','$$']]}}; </script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script><script src="../js/navigation.js"></script><script src="../js/problems.js"></script><script src="../js/quizzes.js"></script></head><body><header><div class="header-content"><h1>MODULE 9: CONTROL THEORY</h1><p class="subtitle">Linear Systems, PID Control, Stability</p></div></header><main class="container"><div class="progress-container"><div class="progress-bar"></div><div class="progress-text">0% Complete</div></div><section class="content-section"><h2>Module Overview</h2><p>Control theory enables hexapods to track trajectories. PID control is standard. Stability analysis ensures safe operation. Frequency-domain design provides insight.</p><div class="important-box"><h3>PID Control</h3><p>\(u = K_p e + K_i\int e dt + K_d de/dt.\) Proportional responds to error, integral eliminates steady-state, derivative adds damping.</p></div><div class="important-box"><h3>Stability</h3><p>All poles in left half-plane (LHP) = stable. Any pole in right half-plane (RHP) = unstable. Poles on imaginary axis = marginally stable.</p></div><div class="important-box"><h3>Frequency Response</h3><p>Bode plots: magnitude 20log|G(jw)| and phase vs frequency. Gain margin > 6 dB, phase margin > 30° typical.</p></div><section class="quiz-section"><h2>Module Quiz</h2><div id="quiz-container"></div><button class="submit" onclick="module9Quiz()">Submit Quiz</button><div id="quiz-results"></div></section><div class="nav-buttons"><button class="secondary" onclick="navigateTo('08-vibrations-waves.html')">Previous</button><button onclick="navigateTo('10-fluid-mechanics.html')">Next</button></div></main><footer><p>Module 9</p></footer><script>function module9Quiz(){submitQuiz('09').percentage>=70&&markModuleComplete('09');}window.addEventListener("load",function(){updateProgressBar();});</script></body></html>
EOF

cat > "$BASE/10-fluid-mechanics.html" << 'EOF'
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Module 10</title><link rel="stylesheet" href="../css/styles.css"><script>MathJax = {tex: {inlineMath: [['\\(','\\)']], displayMath: [['$$','$$']]}}; </script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script><script src="../js/navigation.js"></script><script src="../js/problems.js"></script><script src="../js/quizzes.js"></script></head><body><header><div class="header-content"><h1>MODULE 10: FLUID MECHANICS</h1><p class="subtitle">Bernoulli, Reynolds Number, Drag</p></div></header><main class="container"><div class="progress-container"><div class="progress-bar"></div><div class="progress-text">0% Complete</div></div><section class="content-section"><h2>Module Overview</h2><p>While less directly applicable to terrestrial hexapods, fluid mechanics informs hydraulic actuation and drag. Bernoulli equation governs energy conservation in fluid flow.</p><div class="important-box"><h3>Bernoulli Equation</h3><p>$\(p + \frac{1}{2}\rho v^2 + \rho gh = \text{constant}.\) Pressure + dynamic + gravitational potential along streamline.</p></div><div class="important-box"><h3>Reynolds Number</h3><p>\(Re = \rho v L/\mu.\) \(Re < 2300\): laminar. \(Re > 4000\): turbulent. Ratio of inertial to viscous forces.</p></div><div class="important-box"><h3>Drag Force</h3><p>\(F_D = \frac{1}{2}C_D \rho A v^2.\) Aerodynamic drag increases with \(v^2\).</p></div><section class="quiz-section"><h2>Module Quiz</h2><div id="quiz-container"></div><button class="submit" onclick="module10Quiz()">Submit Quiz</button><div id="quiz-results"></div></section><div class="nav-buttons"><button class="secondary" onclick="navigateTo('09-control-theory.html')">Previous</button><button onclick="navigateTo('11-thermodynamics.html')">Next</button></div></main><footer><p>Module 10</p></footer><script>function module10Quiz(){submitQuiz('10').percentage>=70&&markModuleComplete('10');}window.addEventListener("load",function(){updateProgressBar();});</script></body></html>
EOF

cat > "$BASE/11-thermodynamics.html" << 'EOF'
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Module 11</title><link rel="stylesheet" href="../css/styles.css"><script>MathJax = {tex: {inlineMath: [['\\(','\\)']], displayMath: [['$$','$$']]}}; </script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script><script src="../js/navigation.js"></script><script src="../js/problems.js"></script><script src="../js/quizzes.js"></script></head><body><header><div class="header-content"><h1>MODULE 11: THERMODYNAMICS</h1><p class="subtitle">Heat Transfer, Thermal Management</p></div></header><main class="container"><div class="progress-container"><div class="progress-bar"></div><div class="progress-text">0% Complete</div></div><section class="content-section"><h2>Module Overview</h2><p>Thermal management prevents overheating of motors and electronics. Understanding heat transfer mechanisms ensures reliable operation.</p><div class="important-box"><h3>First Law</h3><p>\(\Delta U = Q - W.\) Change in internal energy = heat added minus work done by system.</p></div><div class="important-box"><h3>Heat Transfer Modes</h3><p>Conduction: \(q = -k dT/dx\) (Fourier). Convection: \(q = hA(T_s - T_f)\) (Newton\'s). Radiation: \(P = \varepsilon\sigma A T^4\) (Stefan-Boltzmann).</p></div><section class="quiz-section"><h2>Module Quiz</h2><div id="quiz-container"></div><button class="submit" onclick="module11Quiz()">Submit Quiz</button><div id="quiz-results"></div></section><div class="nav-buttons"><button class="secondary" onclick="navigateTo('10-fluid-mechanics.html')">Previous</button><button onclick="navigateTo('12-hexapod-design.html')">Next</button></div></main><footer><p>Module 11</p></footer><script>function module11Quiz(){submitQuiz('11').percentage>=70&&markModuleComplete('11');}window.addEventListener("load",function(){updateProgressBar();});</script></body></html>
EOF

cat > "$BASE/12-hexapod-design.html" << 'EOF'
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Module 12</title><link rel="stylesheet" href="../css/styles.css"><script>MathJax = {tex: {inlineMath: [['\\(','\\)']], displayMath: [['$$','$$']]}}; </script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script><script src="../js/navigation.js"></script><script src="../js/problems.js"></script><script src="../js/quizzes.js"></script></head><body><header><div class="header-content"><h1>MODULE 12: HEXAPOD DESIGN & GAITS</h1><p class="subtitle">Leg Kinematics, Gait Patterns, Stability</p></div></header><main class="container"><div class="progress-container"><div class="progress-bar"></div><div class="progress-text">0% Complete</div></div><section class="content-section"><h2>Module Overview</h2><p>Capstone module combining all prior knowledge. Focused on hexapod-specific design: leg kinematics, gait planning, static stability.</p><div class="important-box"><h3>Leg Kinematics</h3><p>Hexapod has 18 DOFs: 6 legs × 3 joints. Three-joint leg provides position control in x,y,z. Inverse kinematics: desired foot position → joint angles.</p></div><div class="important-box"><h3>Tripod Gait</h3><p>Groups (1,4,5) and (2,3,6) alternate. At any time, 3 legs on ground forming stable triangle. COM projection always within support polygon.</p></div><section class="quiz-section"><h2>Module Quiz</h2><div id="quiz-container"></div><button class="submit" onclick="module12Quiz()">Submit Quiz</button><div id="quiz-results"></div></section><div class="nav-buttons"><button class="secondary" onclick="navigateTo('11-thermodynamics.html')">Previous</button><button onclick="navigateTo('13-final.html')">Next</button></div></main><footer><p>Module 12</p></footer><script>function module12Quiz(){submitQuiz('12').percentage>=70&&markModuleComplete('12');}window.addEventListener("load",function(){updateProgressBar();});</script></body></html>
EOF

cat > "$BASE/13-final.html" << 'EOF'
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Module 13</title><link rel="stylesheet" href="../css/styles.css"><script>MathJax = {tex: {inlineMath: [['\\(','\\)']], displayMath: [['$$','$$']]}}; </script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script><script src="../js/navigation.js"></script><script src="../js/problems.js"></script><script src="../js/quizzes.js"></script></head><body><header><div class="header-content"><h1>MODULE 13: REVIEW & FINAL ASSESSMENT</h1><p class="subtitle">Comprehensive Review, Final Exam</p></div></header><main class="container"><div class="progress-container"><div class="progress-bar"></div><div class="progress-text">0% Complete</div></div><section class="content-section"><h2>Module Overview</h2><p>Congratulations on completing all 12 modules! This final module provides comprehensive review and 25-question comprehensive final exam. 80% needed to pass.</p><div class="important-box"><h3>Key Concepts</h3><ul><li>Math: vectors, matrices, calculus</li><li>Mechanics: \(F = ma\), \(\tau = I\alpha\)</li><li>Electronics: circuits, motors, sensors</li><li>Control: PID, stability, frequency response</li><li>Materials: stress, strain, fatigue</li><li>Hexapod: IK, gaits, stability</li></ul></div><section class="quiz-section"><h2>Final Exam</h2><p>25 questions covering all course material. 80% required to pass.</p><div id="quiz-container"></div><button class="submit" onclick="finalExam()">Submit Final Exam</button><div id="quiz-results"></div></section><div class="nav-buttons"><button class="secondary" onclick="navigateTo('12-hexapod-design.html')">Previous</button><button onclick="navigateTo('../index.html')">Back to Course Home</button></div></main><footer><p>Module 13</p></footer><script>function finalExam(){const result=submitQuiz('final');if(result.percentage>=80)markModuleComplete('13');}window.addEventListener("load",function(){updateProgressBar();});</script></body></html>
EOF

echo "All remaining modules (7-13) created successfully!"